extends:
  - "https://github.com/markormesher/tedium-config"

chores:
  - url: "https://github.com/markormesher/tedium-chores"
    directory: "generate-taskfile"
  - url: "https://github.com/markormesher/task-fetcher"
    directory: "chores/update-task"
