# This file is maintained by Tedium - manual edits will be overwritten!

version: "2.1"
jobs:
  checkout:
    docker:
      - image: cimg/base:2024.12
    steps:
      - checkout:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - .
  ci-all:
    docker:
      - image: cimg/base:2024.12
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "Done"
  fetch-task:
    docker:
      - image: ghcr.io/markormesher/task-fetcher:v0.4.1
    steps:
      - attach_workspace:
          at: .
      - run:
          command: cp /task .
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  main:
    jobs:
      - checkout:
          requires: []
          filters:
            tags:
              only: /.*/
      - fetch-task:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
      - ci-all:
          requires:
            - checkout
            - fetch-task
          filters:
            tags:
              only: /.*/
