name: "CI"

on:
  - "push"

jobs:
  debug:
    runs-on: "ubuntu-latest"
    container:
      image: "docker.io/golang:1.26.4@sha256:68cb6d68bed024785b69195b89af7ac7a444f27791435f98647edff595aa0479"
    steps:
      - uses: "markormesher/ci-resources/setup@2e0c5b4e20ae03ad16b60dff677705ba442e172d"
      - run: "task --list-all"

  imgbuild:
    runs-on: "docker"
    needs:
      - "debug"
    container:
      image: "quay.io/buildah/stable"
    steps:
      - uses: "markormesher/ci-resources/setup@2e0c5b4e20ae03ad16b60dff677705ba442e172d"
      - run: "task imgrefs"
      - run: "task imgbuild"
      - run: "task imgpush"

  ci-all:
    runs-on: "docker"
    needs:
      - "debug"
      - "imgbuild"
    container:
      image: "docker.io/busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d"
    steps:
      - run: "echo Done"
